///////////////////////////////////////////////////////////
//  GiaoDichTienTe.cs
//  Implementation of the Class GiaoDichTienTe
//  Generated by Enterprise Architect
//  Created on:      18-Sep-2026 2:51:24 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Model.Bai_03;
namespace Model.Bai_03
{
    // Lớp mô tả giao dịch tiền tệ, kế thừa từ lớp GiaoDich.
    public class GiaoDichTienTe : GiaoDich
    {
        // ===== THUỘC TÍNH RIÊNG =====
        private double tiGia;
        private string loaiTienTe;

        // ===== CONSTRUCTOR =====
        // Constructor default gọi constructor của lớp cha.
        public GiaoDichTienTe() : base()
        {
            tiGia = 1;
            loaiTienTe = string.Empty;
        }

        // Constructor Parameter
        public GiaoDichTienTe(string maGiaoDich, DateOnly ngayGiaoDich, double donGia, int soLuong, double tiGia, string loaiTienTe)
            : base(maGiaoDich, ngayGiaoDich, donGia, soLuong)
        {
            this.tiGia = tiGia;
            this.loaiTienTe = loaiTienTe;
        }

        // ===== PROPERTY =====
        public double TiGia => tiGia;
        public string LoaiTienTe => loaiTienTe;

        // ===== PHƯƠNG THỨC =====
        // VND: số lượng * đơn giá.
        // USD/Euro: số lượng * đơn giá * tỉ giá.
        public override double GetThanhTien()
        {
            if (loaiTienTe.Equals("VND", StringComparison.OrdinalIgnoreCase))
            {
                return SoLuong * DonGia;
            }

            return SoLuong * DonGia * tiGia;
        }

        // Trả về thông tin giao dịch tiền tệ dạng chuỗi.
        public override string ToString()
        {
            return $"Mã giao dịch: {MaGiaoDich} | " +
                   $"Ngày giao dịch: {NgayGiaoDich:dd/MM/yyyy} | " +
                   $"Đơn giá: {DonGia:N0} | " +
                   $"Số lượng: {SoLuong} | " +
                   $"Tỉ giá: {tiGia:N0} | " +
                   $"Loại tiền tệ: {loaiTienTe} | " +
                   $"Thành tiền: {GetThanhTien():N0}";
        }
    }
}
