///////////////////////////////////////////////////////////
//  GiaoDichVang.cs
//  Implementation of the Class GiaoDichVang
//  Generated by Enterprise Architect
//  Created on:      18-Sep-2026 2:51:13 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Model.Bai_03;
namespace Model.Bai_03
{
    // Lớp mô tả giao dịch vàng, kế thừa từ lớp GiaoDich.
    public class GiaoDichVang : GiaoDich
    {
        // ===== THUỘC TÍNH RIÊNG =====
        private string loaiVang;

        // ===== CONSTRUCTOR =====
        // Constructor default gọi constructor của lớp cha.
        public GiaoDichVang() : base()
        {
            loaiVang = string.Empty;
        }

        // Constructor Parameter
        public GiaoDichVang(string maGiaoDich, DateOnly ngayGiaoDich, double donGia, int soLuong, string loaiVang)
            : base(maGiaoDich, ngayGiaoDich, donGia, soLuong)
        {
            this.loaiVang = loaiVang;
        }

        // ===== PROPERTY =====
        public string LoaiVang => loaiVang;

        // ===== PHƯƠNG THỨC =====
        // Thành tiền giao dịch vàng = số lượng * đơn giá.
        public override double GetThanhTien()
        {
            return SoLuong * DonGia;
        }

        // Trả về thông tin giao dịch vàng dạng chuỗi.
        public override string ToString()
        {
            return $"Mã giao dịch: {MaGiaoDich} | " +
                   $"Ngày giao dịch: {NgayGiaoDich:dd/MM/yyyy} | " +
                   $"Đơn giá: {DonGia:N0} | " +
                   $"Số lượng: {SoLuong} | " +
                   $"Loại vàng: {loaiVang} | " +
                   $"Thành tiền: {GetThanhTien():N0}";
        }
    }
}
