///////////////////////////////////////////////////////////
//  GiaoDich.cs
//  Implementation of the Class GiaoDich
//  Generated by Enterprise Architect
//  Created on:      18-Sep-2026 2:51:06 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Model.Bai_03
{
    // Lớp cha abstract chứa các thông tin chung của mọi giao dịch.
    public abstract class GiaoDich
    {
        // ===== THUỘC TÍNH =====
        private string maGiaoDich;
        private DateOnly ngayGiaoDich;
        private double donGia;
        private int soLuong;

        // ===== CONSTRUCTOR =====
        // Constructor default.
        public GiaoDich()
        {
            maGiaoDich = string.Empty;
            ngayGiaoDich = DateOnly.FromDateTime(DateTime.Now);
            donGia = 0;
            soLuong = 0;
        }

        // Constructor Parameter.
        public GiaoDich(string maGiaoDich, DateOnly ngayGiaoDich, double donGia, int soLuong)
        {
            this.maGiaoDich = maGiaoDich;
            this.ngayGiaoDich = ngayGiaoDich;
            this.donGia = donGia;
            this.soLuong = soLuong;
        }

        // ===== PROPERTY =====
        // Các thuộc tính chỉ cho phép đọc dữ liệu từ bên ngoài lớp.
        public string MaGiaoDich => maGiaoDich;
        public DateOnly NgayGiaoDich => ngayGiaoDich;
        public double DonGia => donGia;
        public int SoLuong => soLuong;

        // ===== PHƯƠNG THỨC =====
        // Lớp con tự cài đặt công thức tính thành tiền.
        public abstract double GetThanhTien();

        // Lớp con tự định dạng thông tin giao dịch.
        public abstract override string ToString();
    }
}
