///////////////////////////////////////////////////////////
//  Program.cs
//  Implementation of the Class Program
//  Generated by Enterprise Architect
//  Created on:      18-Sep-2026 2:51:31 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Model.Bai_03;
namespace Model.Bai_03
{
    public class Program
    {
        
        public static void Main(string[] args)
        {
            Console.OutputEncoding = Encoding.UTF8;

            // Tạo sẵn 3 giao dịch vàng và 3 giao dịch tiền tệ.
            GiaoDich[] danhSach =
            {
                new GiaoDichVang("V001", new DateOnly(2024, 1, 10), 85000000, 2, "SJC"),
                new GiaoDichVang("V002", new DateOnly(2024, 2, 15), 76000000, 3, "9999"),
                new GiaoDichVang("V003", new DateOnly(2024, 3, 20), 1200000000, 1, "PNJ"),

                new GiaoDichTienTe("T001", new DateOnly(2024, 1, 5), 24000, 1000, 1, "VND"),
                new GiaoDichTienTe("T002", new DateOnly(2024, 2, 12), 1, 500, 24500, "USD"),
                new GiaoDichTienTe("T003", new DateOnly(2024, 3, 18), 1, 300, 26500, "Euro")
            };

            // Xuất toàn bộ giao dịch; đây là cách sử dụng tính đa hình.
            Console.WriteLine("========== DANH SÁCH GIAO DỊCH ==========");
            foreach (GiaoDich giaoDich in danhSach)
            {
                Console.WriteLine(giaoDich);
            }

            Console.WriteLine("\n========== THỐNG KÊ ==========");
            Console.WriteLine($"Tổng số lượng giao dịch vàng: {TinhTongSoLuongVang(danhSach)}");
            Console.WriteLine($"Tổng số lượng giao dịch tiền tệ: {TinhTongSoLuongTienTe(danhSach)}");
            Console.WriteLine($"Trung bình thành tiền giao dịch tiền tệ: {TinhTrungBinhThanhTienTienTe(danhSach):N0}");

            // Xuất các giao dịch có đơn giá lớn hơn 1 tỷ.
            Console.WriteLine("\n========== GIAO DỊCH CÓ ĐƠN GIÁ > 1 TỶ ==========");
            XuatGiaoDichDonGiaLon(danhSach);
        }

        // ===== CÁC PHƯƠNG THỨC XỬ LÝ =====
        // Tính tổng số lượng của các giao dịch vàng.
        public static int TinhTongSoLuongVang(GiaoDich[] danhSach)
        {
            int tongSoLuong = 0;

            foreach (GiaoDich giaoDich in danhSach)
            {
                if (giaoDich is GiaoDichVang)
                {
                    tongSoLuong += giaoDich.SoLuong;
                }
            }

            return tongSoLuong;
        }

        // Tính tổng số lượng của các giao dịch tiền tệ.
        public static int TinhTongSoLuongTienTe(GiaoDich[] danhSach)
        {
            int tongSoLuong = 0;

            foreach (GiaoDich giaoDich in danhSach)
            {
                if (giaoDich is GiaoDichTienTe)
                {
                    tongSoLuong += giaoDich.SoLuong;
                }
            }

            return tongSoLuong;
        }

        // Tính trung bình thành tiền của các giao dịch tiền tệ.
        public static double TinhTrungBinhThanhTienTienTe(GiaoDich[] danhSach)
        {
            double tongThanhTien = 0;
            int soLuongGiaoDichTienTe = 0;

            foreach (GiaoDich giaoDich in danhSach)
            {
                if (giaoDich is GiaoDichTienTe)
                {
                    tongThanhTien += giaoDich.GetThanhTien();
                    soLuongGiaoDichTienTe++;
                }
            }

            if (soLuongGiaoDichTienTe == 0)
            {
                return 0;
            }

            return tongThanhTien / soLuongGiaoDichTienTe;
        }

        // In các giao dịch có đơn giá lớn hơn 1 tỷ đồng.
        public static void XuatGiaoDichDonGiaLon(GiaoDich[] danhSach)
        {
            bool coGiaoDich = false;

            foreach (GiaoDich giaoDich in danhSach)
            {
                if (giaoDich.DonGia > 1000000000)
                {
                    Console.WriteLine(giaoDich);
                    coGiaoDich = true;
                }
            }

            if (!coGiaoDich)
            {
                Console.WriteLine("Không có giao dịch nào có đơn giá trên 1 tỷ.");
            }
        }
    }
}