///////////////////////////////////////////////////////////
//  ChuyenXe.cs
//  Implementation of the Class ChuyenXe
//  Generated by Enterprise Architect
//  Created on:      16-Sep-2026 2:47:56 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Module3.Bai_01 {
    public abstract class ChuyenXe
    {
        protected string MaSo;
        protected string HoTenTaiXe;
        protected string SoXe;
        protected double DoanhThu;

        public ChuyenXe()
        {
            MaSo = "";
            HoTenTaiXe = "";
            SoXe = "";
            DoanhThu = 0;
        }

        public ChuyenXe(string maSo, string hoTenTaiXe,
                        string soXe, double doanhThu)
        {
            this.MaSo = maSo;
            this.HoTenTaiXe = hoTenTaiXe;
            this.SoXe = soXe;
            this.DoanhThu = doanhThu;
        }

        public double GetDoanhThu()
        {
            return DoanhThu;
        }

        public abstract override string ToString();
    }

}