///////////////////////////////////////////////////////////
//  ChuyenXeNgoaiThanh.cs
//  Implementation of the Class ChuyenXeNgoaiThanh
//  Generated by Enterprise Architect
//  Created on:      16-Sep-2026 2:46:48 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Module3.Bai_01;
namespace Module3.Bai_01 {
    public class ChuyenXeNgoaiThanh : ChuyenXe
    {
        private string NoiDen;
        private int SoNgay;

        public ChuyenXeNgoaiThanh() : base()
        {
            NoiDen = "";
            SoNgay = 0;
        }

        public ChuyenXeNgoaiThanh(string maSo, string hoTenTaiXe,
                string soXe, double doanhThu,
                string noiDen, int soNgay)
            : base(maSo, hoTenTaiXe, soXe, doanhThu)
        {
            this.NoiDen = noiDen;
            this.SoNgay = soNgay;
        }

        public string GetNoiDen() { return NoiDen; }
        public int GetSoNgay() { return SoNgay; }

        public override string ToString()
        {
            return string.Format(
                "[Ngoại thành] Mã: {0,-6} | Tài xế: {1,-15} | Số xe: {2,-10} | Nơi đến: {3,-10} | Ngày: {4,2} | DT: {5,12:N0} VND",
                MaSo, HoTenTaiXe, SoXe, NoiDen, SoNgay, DoanhThu
            );
        }
    }

}