///////////////////////////////////////////////////////////
//  SachThamKhao.cs
//  Implementation of the Class SachThamKhao
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:40:23 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Model.Bai_02;
namespace Model.Bai_02
{
    // Lớp mô tả sách tham khảo, kế thừa từ lớp Sach.
    public class SachThamKhao : Sach
    {
        // ===== THUỘC TÍNH RIÊNG =====
        private double thue;

        // ===== CONSTRUCTOR =====
        public SachThamKhao() : base()
        {
            thue = 0;
        }

        public SachThamKhao(string maSach, DateOnly ngayNhap, double donGia,
                             int soLuong, string nhaXuatBan, double thue)
            : base(maSach, ngayNhap, donGia, soLuong, nhaXuatBan)
        {
            this.thue = thue;
        }

        // ===== PROPERTY =====
        public double Thue => thue;

        // ===== PHƯƠNG THỨC =====
        // Thành tiền = số lượng * đơn giá + thuế.
        public override double GetThanhTien()
        {
            return soLuong * donGia + thue;
        }

        public override string ToString()
        {
            return $"Mã sách: {maSach} | " +
                   $"Ngày nhập: {ngayNhap:dd/MM/yyyy} | " +
                   $"Đơn giá: {donGia:N0} | " +
                   $"Số lượng: {soLuong} | " +
                   $"NXB: {nhaXuatBan} | " +
                   $"Thuế: {thue:N0} | " +
                   $"Thành tiền: {GetThanhTien():N0}";
        }
    }
}