///////////////////////////////////////////////////////////
//  Sach.cs
//  Implementation of the Class Sach
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:44:44 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Model.Bai_02
{
    public abstract class Sach
    {
        // Fields
        private string maSach;
        private DateOnly ngayNhap;
        private double donGia;
        private int soLuong;
        private string nhaXuatBan;

        // Properties
        public string MaSach
        {
            get { return maSach; }
            set { maSach = value; }
        }

        public DateOnly NgayNhap
        {
            get { return ngayNhap; }
            set { ngayNhap = value; }
        }

        public double DonGia
        {
            get { return donGia; }
            set
            {
                if (value >= 0)
                    donGia = value;
            }
        }

        public int SoLuong
        {
            get { return soLuong; }
            set
            {
                if (value >= 0)
                    soLuong = value;
            }
        }

        public string NhaXuatBan
        {
            get { return nhaXuatBan; }
            set { nhaXuatBan = value; }
        }

        // Constructor default
        public Sach()
        {
            maSach = "";
            ngayNhap = DateOnly.FromDateTime(DateTime.Now);
            donGia = 0;
            soLuong = 0;
            nhaXuatBan = "";
        }

        // Constructor Parameter
        public Sach(
            string maSach,
            DateOnly ngayNhap,
            double donGia,
            int soLuong,
            string nhaXuatBan)
        {
            MaSach = maSach;
            NgayNhap = ngayNhap;
            DonGia = donGia;
            SoLuong = soLuong;
            NhaXuatBan = nhaXuatBan;
        }

        // Abstract methods
        public abstract double GetThanhTien();

        public abstract override string ToString();
    }
}