///////////////////////////////////////////////////////////
//  SachThamKhao.cs
//  Implementation of the Class SachThamKhao
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:40:23 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Model.Bai_02;
namespace Model.Bai_02
{
    /// <summary>
    /// Sách tham khảo — thành tiền = SoLuong * DonGia + Thue
    /// </summary>
    public class SachThamKhao : Sach
    {
        // ===== FIELD =====
        private double thue;

        // ===== PROPERTY =====
        public double Thue
        {
            get { return thue; }
            set
            {
                if (value >= 0)
                    thue = value;
            }
        }

        // ===== CONSTRUCTOR =====
        public SachThamKhao() : base()
        {
            thue = 0;
        }

        public SachThamKhao(string maSach, DateTime ngayNhap,
                double donGia, int soLuong,
                string nhaXuatBan, double thue)
            : base(maSach, ngayNhap, donGia, soLuong, nhaXuatBan)
        {
            Thue = thue;
        }

        // ===== PHƯƠNG THỨC =====
        /// <summary>
        /// ThanhTien = SoLuong * DonGia + Thue
        /// </summary>
        public override double GetThanhTien()
        {
            return SoLuong * DonGia + thue;
        }

        public override string ToString()
        {
            return string.Format(
                "STK | Mã: {0,-8} | NXB: {1,-15} | " +
                "Ngày: {2:dd/MM/yyyy} | SL: {3,3} | " +
                "Đơn giá: {4,10:N0} | Thuế: {5,10:N0} | " +
                "Thành tiền: {6,12:N0} VND",
                MaSach, NhaXuatBan,
                NgayNhap, SoLuong,
                DonGia, thue,
                GetThanhTien()
            );
        }
    }
}