///////////////////////////////////////////////////////////
//  Sach.cs
//  Implementation of the Class Sach
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:44:44 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Model.Bai_02
{
    // Lớp cha abstract chứa thông tin chung của mọi loại sách.
    public abstract class Sach
    {
        // ===== THUỘC TÍNH =====
        protected string maSach;
        protected DateOnly ngayNhap;
        protected double donGia;
        protected int soLuong;
        protected string nhaXuatBan;

        // ===== CONSTRUCTOR =====
        protected Sach()
        {
            maSach = string.Empty;
            ngayNhap = DateOnly.FromDateTime(DateTime.Now);
            donGia = 0;
            soLuong = 0;
            nhaXuatBan = string.Empty;
        }

        protected Sach(string maSach, DateOnly ngayNhap, double donGia, int soLuong, string nhaXuatBan)
        {
            this.maSach = maSach;
            this.ngayNhap = ngayNhap;
            this.donGia = donGia;
            this.soLuong = soLuong;
            this.nhaXuatBan = nhaXuatBan;
        }

        // ===== PROPERTY (chỉ đọc) =====
        public string MaSach => maSach;
        public DateOnly NgayNhap => ngayNhap;
        public double DonGia => donGia;
        public int SoLuong => soLuong;
        public string NhaXuatBan => nhaXuatBan;

        // ===== PHƯƠNG THỨC TRỪU TƯỢNG =====
        // Lớp con tự cài đặt công thức tính thành tiền riêng.
        public abstract double GetThanhTien();

        // Lớp con tự định dạng thông tin sách.
        public abstract override string ToString();
    }
}