///////////////////////////////////////////////////////////
//  SachGiaoKhoa.cs
//  Implementation of the Class SachGiaoKhoa
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:40:29 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Model.Bai_02;
namespace Model.Bai_02
{
    // Lớp mô tả sách giáo khoa, kế thừa từ lớp Sach.
    public class SachGiaoKhoa : Sach
    {
        // ===== THUỘC TÍNH RIÊNG =====
        private bool tinhTrang; // true = mới, false = cũ

        // ===== CONSTRUCTOR =====
        public SachGiaoKhoa() : base()
        {
            tinhTrang = true;
        }

        public SachGiaoKhoa(string maSach, DateOnly ngayNhap, double donGia,
                             int soLuong, string nhaXuatBan, bool tinhTrang)
            : base(maSach, ngayNhap, donGia, soLuong, nhaXuatBan)
        {
            this.tinhTrang = tinhTrang;
        }

        // ===== PROPERTY =====
        public bool TinhTrang => tinhTrang;

        // ===== PHƯƠNG THỨC =====
        // Mới: thành tiền = số lượng * đơn giá.
        // Cũ: thành tiền = số lượng * đơn giá * 50%.
        public override double GetThanhTien()
        {
            if (tinhTrang)
            {
                return soLuong * donGia;
            }

            return soLuong * donGia * 0.5;
        }

        public override string ToString()
        {
            return $"Mã sách: {maSach} | " +
                   $"Ngày nhập: {ngayNhap:dd/MM/yyyy} | " +
                   $"Đơn giá: {donGia:N0} | " +
                   $"Số lượng: {soLuong} | " +
                   $"NXB: {nhaXuatBan} | " +
                   $"Tình trạng: {(tinhTrang ? "Mới" : "Cũ")} | " +
                   $"Thành tiền: {GetThanhTien():N0}";
        }
    }
}