///////////////////////////////////////////////////////////
//  SachThamKhao.cs
//  Implementation of the Class SachThamKhao
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:40:23 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Model.Bai_02;
namespace Model.Bai_02
{
    public class SachThamKhao : Sach
    {
        // Field
        private double thue;

        // Property
        public double Thue
        {
            get { return thue; }
            set
            {
                if (value >= 0)
                    thue = value;
            }
        }

        // Constructor mặc định
        public SachThamKhao() : base()
        {
            thue = 0;
        }

        // Constructor đầy đủ tham số
        public SachThamKhao(
            string maSach,
            DateOnly ngayNhap,
            double donGia,
            int soLuong,
            string nhaXuatBan,
            double thue)
            : base(maSach, ngayNhap, donGia, soLuong, nhaXuatBan)
        {
            Thue = thue;
        }

        // Tính thành tiền
        public override double GetThanhTien()
        {
            return SoLuong * DonGia + thue;
        }

        // Xuất thông tin
        public override string ToString()
        {
            return string.Format(
                "STK | Mã: {0,-8} | NXB: {1,-15} | " +
                "Ngày: {2:dd/MM/yyyy} | SL: {3,3} | " +
                "Đơn giá: {4,10:N0} | Thuế: {5,10:N0} | " +
                "Thành tiền: {6,12:N0} VND",
                MaSach,
                NhaXuatBan,
                NgayNhap,
                SoLuong,
                DonGia,
                thue,
                GetThanhTien()
            );
        }
    }
}