///////////////////////////////////////////////////////////
//  Sach.cs
//  Implementation of the Class Sach
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:44:44 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Model.Bai_02
{
    /// <summary>
    /// Lớp cha abstract mô tả thông tin chung của một cuốn sách
    /// </summary>
    public abstract class Sach
    {
        // ===== FIELDS =====
        private string maSach;
        private DateTime ngayNhap;
        private double donGia;
        private int soLuong;
        private string nhaXuatBan;

        // ===== PROPERTIES =====
        public string MaSach
        {
            get { return maSach; }
            set { maSach = value; }
        }

        public DateTime NgayNhap
        {
            get { return ngayNhap; }
            set { ngayNhap = value; }
        }

        public double DonGia
        {
            get { return donGia; }
            set
            {
                if (value >= 0)
                    donGia = value;
            }
        }

        public int SoLuong
        {
            get { return soLuong; }
            set
            {
                if (value >= 0)
                    soLuong = value;
            }
        }

        public string NhaXuatBan
        {
            get { return nhaXuatBan; }
            set { nhaXuatBan = value; }
        }

        // ===== CONSTRUCTOR =====
        public Sach()
        {
            maSach = "";
            ngayNhap = DateTime.Now;
            donGia = 0;
            soLuong = 0;
            nhaXuatBan = "";
        }

        public Sach(string maSach, DateTime ngayNhap,
                    double donGia, int soLuong,
                    string nhaXuatBan)
        {
            MaSach = maSach;
            NgayNhap = ngayNhap;
            DonGia = donGia;
            SoLuong = soLuong;
            NhaXuatBan = nhaXuatBan;
        }

        // ===== PHƯƠNG THỨC ABSTRACT =====
        public abstract override string ToString();
        public abstract double GetThanhTien();
    }
}