///////////////////////////////////////////////////////////
//  SachGiaoKhoa.cs
//  Implementation of the Class SachGiaoKhoa
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:40:29 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Model.Bai_02;
namespace Model.Bai_02
{
    public class SachGiaoKhoa : Sach
    {
        // Field
        private bool tinhTrang;

        // Property
        public bool TinhTrang
        {
            get { return tinhTrang; }
            set { tinhTrang = value; }
        }

        // Constructor default
        public SachGiaoKhoa() : base()
        {
            tinhTrang = true;
        }

        // Constructor parameter
        public SachGiaoKhoa(
            string maSach,
            DateOnly ngayNhap,
            double donGia,
            int soLuong,
            string nhaXuatBan,
            bool tinhTrang)
            : base(maSach, ngayNhap, donGia, soLuong, nhaXuatBan)
        {
            TinhTrang = tinhTrang;
        }

        // Tính thành tiền
        public override double GetThanhTien()
        {
            return tinhTrang
                ? SoLuong * DonGia
                : SoLuong * DonGia * 0.5;
        }

        // Xuất thông tin
        public override string ToString()
        {
            return string.Format(
                "SGK | Mã: {0,-8} | NXB: {1,-15} | " +
                "Ngày: {2:dd/MM/yyyy} | SL: {3,3} | " +
                "Đơn giá: {4,10:N0} | Tình trạng: {5,-4} | " +
                "Thành tiền: {6,12:N0} VND",
                MaSach,
                NhaXuatBan,
                NgayNhap,
                SoLuong,
                DonGia,
                tinhTrang ? "Mới" : "Cũ",
                GetThanhTien()
            );
        }
    }
}