///////////////////////////////////////////////////////////
//  ChuyenXe.cs
//  Implementation of the Class ChuyenXe
//  Generated by Enterprise Architect
//  Created on:      16-Sep-2026 2:47:56 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Model.Bai_01
{
    // Lớp cha abstract mô tả thông tin chung của một chuyến xe.
    public abstract class ChuyenXe
    {
        // ===== THUỘC TÍNH =====
        protected string maSo;
        protected string hoTenTaiXe;
        protected string soXe;
        protected double doanhThu;

        // ===== CONSTRUCTOR =====
        protected ChuyenXe()
        {
            maSo = string.Empty;
            hoTenTaiXe = string.Empty;
            soXe = string.Empty;
            doanhThu = 0;
        }

        protected ChuyenXe(string maSo, string hoTenTaiXe, string soXe, double doanhThu)
        {
            this.maSo = maSo;
            this.hoTenTaiXe = hoTenTaiXe;
            this.soXe = soXe;
            this.doanhThu = doanhThu >= 0 ? doanhThu : 0;
        }

        // ===== PROPERTY (chỉ đọc) =====
        public string MaSo => maSo;
        public string HoTenTaiXe => hoTenTaiXe;
        public string SoXe => soXe;
        public double DoanhThu => doanhThu;

        // ===== PHƯƠNG THỨC =====
        // Lớp con tự định dạng thông tin hiển thị riêng.
        public abstract override string ToString();
    }
}