///////////////////////////////////////////////////////////
//  ChuyenXe.cs
//  Implementation of the Class ChuyenXe
//  Generated by Enterprise Architect
//  Created on:      16-Sep-2026 2:47:56 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Model.Bai_01
{
    /// <summary>
    /// Lớp cha abstract mô tả thông tin chung của một chuyến xe
    /// </summary>
    public abstract class ChuyenXe
    {
        // ===== THUỘC TÍNH =====
        private string maSo;
        private string hoTenTaiXe;
        private string soXe;
        private double doanhThu;

        // ===== PROPERTY =====
        public string MaSo
        {
            get { return maSo; }
            set { maSo = value; }
        }

        public string HoTenTaiXe
        {
            get { return hoTenTaiXe; }
            set { hoTenTaiXe = value; }
        }

        public string SoXe
        {
            get { return soXe; }
            set { soXe = value; }
        }

        public double DoanhThu
        {
            get { return doanhThu; }
            set
            {
                if (value >= 0)
                    doanhThu = value;
            }
        }

        // ===== CONSTRUCTOR =====
        /// <summary>Constructor default</summary>
        public ChuyenXe()
        {
            maSo = "";
            hoTenTaiXe = "";
            soXe = "";
            doanhThu = 0;
        }

        /// <summary>Constructor Parameter</summary>
        public ChuyenXe(string maSo, string hoTenTaiXe,
                        string soXe, double doanhThu)
        {
            MaSo = maSo;
            HoTenTaiXe = hoTenTaiXe;
            SoXe = soXe;
            DoanhThu = doanhThu;
        }

        // ===== PHƯƠNG THỨC =====
  
        public abstract override string ToString();
    }
}