///////////////////////////////////////////////////////////
//  ChuyenXeNoiThanh.cs
//  Implementation of the Class ChuyenXeNoiThanh
//  Generated by Enterprise Architect
//  Created on:      16-Sep-2026 2:46:42 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Model.Bai_01
{
    // Lớp mô tả chuyến xe nội thành, kế thừa từ lớp ChuyenXe.
    public class ChuyenXeNoiThanh : ChuyenXe
    {
        // ===== THUỘC TÍNH RIÊNG =====
        private string soTuyen;
        private double soKm;

        // ===== CONSTRUCTOR =====
        public ChuyenXeNoiThanh() : base()
        {
            soTuyen = string.Empty;
            soKm = 0;
        }

        public ChuyenXeNoiThanh(string maSo, string hoTenTaiXe, string soXe,
                                 double doanhThu, string soTuyen, double soKm)
            : base(maSo, hoTenTaiXe, soXe, doanhThu)
        {
            this.soTuyen = soTuyen;
            this.soKm = soKm >= 0 ? soKm : 0;
        }

        // ===== PROPERTY =====
        public string SoTuyen => soTuyen;
        public double SoKm => soKm;

        // ===== PHƯƠNG THỨC =====
        public override string ToString()
        {
            return $"[Nội thành] Mã: {maSo} | " +
                   $"Tài xế: {hoTenTaiXe} | " +
                   $"Số xe: {soXe} | " +
                   $"Tuyến: {soTuyen} | " +
                   $"Số km: {soKm:N1} | " +
                   $"Doanh thu: {doanhThu:N0} VND";
        }
    }
}