///////////////////////////////////////////////////////////
//  ChuyenXeNgoaiThanh.cs
//  Implementation of the Class ChuyenXeNgoaiThanh
//  Generated by Enterprise Architect
//  Created on:      16-Sep-2026 2:46:48 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Model.Bai_01
{
    // Lớp mô tả chuyến xe ngoại thành, kế thừa từ lớp ChuyenXe.
    public class ChuyenXeNgoaiThanh : ChuyenXe
    {
        // ===== THUỘC TÍNH RIÊNG =====
        private string noiDen;
        private int soNgay;

        // ===== CONSTRUCTOR =====
        public ChuyenXeNgoaiThanh() : base()
        {
            noiDen = string.Empty;
            soNgay = 0;
        }

        public ChuyenXeNgoaiThanh(string maSo, string hoTenTaiXe, string soXe,
                                   double doanhThu, string noiDen, int soNgay)
            : base(maSo, hoTenTaiXe, soXe, doanhThu)
        {
            this.noiDen = noiDen;
            this.soNgay = soNgay >= 0 ? soNgay : 0;
        }

        // ===== PROPERTY =====
        public string NoiDen => noiDen;
        public int SoNgay => soNgay;

        // ===== PHƯƠNG THỨC =====
        public override string ToString()
        {
            return $"[Ngoại thành] Mã: {maSo} | " +
                   $"Tài xế: {hoTenTaiXe} | " +
                   $"Số xe: {soXe} | " +
                   $"Nơi đến: {noiDen} | " +
                   $"Số ngày: {soNgay} | " +
                   $"Doanh thu: {doanhThu:N0} VND";
        }
    }
}