///////////////////////////////////////////////////////////
//  ChuyenXeNoiThanh.cs
//  Implementation of the Class ChuyenXeNoiThanh
//  Generated by Enterprise Architect
//  Created on:      16-Sep-2026 2:46:42 AM
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Module3.Bai_01;
namespace Module3.Bai_01 {
    public class ChuyenXeNoiThanh : ChuyenXe
    {
        private string SoTuyen;
        private double SoKm;

        public ChuyenXeNoiThanh() : base()
        {
            SoTuyen = "";
            SoKm = 0;
        }

        public ChuyenXeNoiThanh(string maSo, string hoTenTaiXe,
                string soXe, double doanhThu,
                string soTuyen, double soKm)
            : base(maSo, hoTenTaiXe, soXe, doanhThu)
        {
            this.SoTuyen = soTuyen;
            this.SoKm = soKm;
        }

        public string getSoTuyen() { return SoTuyen; }
        public double getSoKm() { return SoKm; }

        public override string ToString()
        {
            return string.Format(
                "[Nội thành]   Mã: {0,-6} | Tài xế: {1,-15} | Số xe: {2,-10} | Tuyến: {3,-8} | Km: {4,6:F1} | DT: {5,12:N0} VND",
                MaSo, HoTenTaiXe, SoXe, SoTuyen, SoKm, DoanhThu
            );
        }
    }

}